CREATE  TABLE `fatec`.`EMPRESTIMO` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NOME` VARCHAR(45) NULL ,
  `LIVRO` DATE NULL ,
  `DATA_EMPRESTIMO` DATE NULL ,
  `DATA_ENTREGA` VARCHAR(45) NULL ,
  `TELEFONE` VARCHAR(45) NULL ,
  `ENDERECO` VARCHAR(45) NULL ,
  `EMAIL` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `ID_PESSOA`
    FOREIGN KEY (`ID` )
    REFERENCES `fatec`.`usuario` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_LIVRO`
    FOREIGN KEY (`ID` )
    REFERENCES `fatec`.`livro` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);