CREATE  TABLE `fatec`.`USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NOME` VARCHAR(45) NULL ,
  `TELEFONE` VARCHAR(45) NULL ,
  `DATA_NASC` VARCHAR(45) NULL ,
  `ENDERECO` VARCHAR(45) NULL ,
  `EMAIL` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) );